### ISSUE TITLE
Проблем с показване на download икони в Edge при режим Висок контраст и тема High Contrast Black

### ISSUE THREAD

**Issue by pistachio-consumer** [chitanka/chitanka#81]
Не знам кой ползва такъв режим, но този проблем беше докладван чрез формата за обратна връзка.
Подобен проблем: https://github.com/eBay/skin/issues/233

Пример сега:
![image](https://user-images.githubusercontent.com/71929928/96938605-7942ad80-14d3-11eb-8f15-9662cf9aaa33.png)

Пример след промяна на CSS правилото за `dd.download`:
![image](https://user-images.githubusercontent.com/71929928/96938648-95464f00-14d3-11eb-99ef-bd7ec65f6daa.png)

Този проблем може да се заобиколи чрез добавянето на `-ms-high-contrast-adjust: none;` към следното CSS правило:
```css
dd.download {
    float: right;
    max-width: 24%;
    margin-right: 0px;
    -ms-high-contrast-adjust: none;
}
```
Доколкото виждам, `dd.download` фигурира в няколко файла: [/web/css/base-screen.less#L484](https://github.com/chitanka/chitanka/blob/47f12726d85ca4c627c339c6282af571ef663bf7/web/css/base-screen.less#L484) и [/web/css/base-screen-800px.less#L49](https://github.com/chitanka/chitanka/blob/47f12726d85ca4c627c339c6282af571ef663bf7/web/css/base-screen-800px.less#L49)
