### ISSUE TITLE
Връзките за сваляне на PDF и MOBI форматите не се появяват след промяна в конфигурацията

### ISSUE THREAD

**Issue by semerdzhiev** [chitanka/chitanka#83]
Здравейте. След обновяване на локално копие на системата на читанката до последната версия и включване на опциите за сваляне на PDF и MOBI в `parameters.yml`, в локалната версия не се показват съответните бутони за сваляне:

![screenshot](https://user-images.githubusercontent.com/7514960/151670336-38dd91ba-783f-4f43-a3e3-2c17ca4524cc.png)

Искам да попитам дали има нещо друго, което трябва да се конфигурира, за да може да се използват опциите за сваляне на тези два формата?

`parameters.yml` изглежда така:

```yml
# Indentation: 4 spaces, NO tabs
# Comments start with #
# Empty values are indicated with ~

# These parameters can be imported into other config files
# by enclosing the key with % (like %database_user%)
parameters:
    database_host: localhost
    database_name: chitanka
    database_user: chitanka
    database_password: chitanka
    database_driver: pdo_mysql
    database_port: null

    secret: ThisTokenIsNotSoSecretChangeIt

    pdf_download_enabled: true
    mobi_download_enabled: true
```

`ebook-convert` също е инсталирана (през calibre) и е добавена в `PATH`.

Благодаря предварително.

**Comment by bmanolov** [comment]
Нужен е и следния параметър, който реално се използва при генерирането на връзките:

```yaml
parameters:
    # ...

    download_formats_external_converter: [pdf, mobi]
```
